<?php
	
	
	function glogin_menu() {
	  $items['game/login'] = array(
	    'title' => 'Login',
	    'description' => 'Custom Login Form',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('glogin_login_form'), // The matched wildcard.
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );
	  
	  $items['game/signup'] = array(
	    'title' => 'Sign Up',
	    'description' => 'Custom Register Form',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('glogin_signup_form'), // The matched wildcard.
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );
	  
	  $items['game/forget-password'] = array(
	    'title' => 'Forget Password',
	    'description' => 'Custom Forget Password Form',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('glogin_fpass_form'), // The matched wildcard.
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );
	  
	  return $items;
	}
	
	function glogin_login_form($form_login, &$form_state) {
		
		$form_login['username'] = array(
			'#type' => 'textfield',
			'#title' => t('Username'),
			'#size' => 10,
			'#required' => TRUE,
		);
		
		$form_login['password'] = array(
			'#type' => 'password',
			'#title' => t('Password'),
			'#size' => 10,
			'#required' => TRUE,
		);
		
		$form_login['submit_button'] = array(
			'#type' => 'submit',
			'#value' => t('Login'),
		);
		
		return $form_login;
	}
	
	function glogin_login_form_submit($form_login, &$form_state) {
		$username = $form_state['values']['username'];
		$password = $form_state['values']['password'];
		
		if(user_authenticate($username, $password)) {
			drupal_set_message(t('Auth Success! User : '. $username .' & Pass : '. $password));	
		} else {
			drupal_set_message(t('Auth Failed! User or Password wrong'));	
		}
		
		
	}
	
	function glogin_signup_form($form_signup, &$form_state) {
		
		$form_signup['name'] = array(
			'#type' => 'textfield',
			'#title' => t('Name'),
			'#size' => 20,
			'#required' => TRUE,
		);
		
		$form_signup['pass'] = array(
			'#type' => 'password',
			'#title' => t('Password'),
			'#size' => 20,
			'#required' => TRUE,
		);
		
		$form_signup['email'] = array(
			'#type' => 'textfield',
			'#title' => t('E-mail'),
			'#size' => 20,
			'#required' => TRUE,
		);
		
		$form_signup['submit_button'] = array(
			'#type' => 'submit',
			'#value' => t('Sign Up'),
		);
		
		return $form_signup;
	}
	
	function glogin_signup_form_submit($form_signup, &$form_state) {
		$field = array(
			'name' => $form_state['values']['name'],
			'mail' => $form_state['values']['email'],
			'pass' => $form_state['values']['pass'],
			'status' => 1,
			'init' => $form_state['values']['email'],
			'roles' => array(
		    	DRUPAL_AUTHENTICATED_RID => 'authenticated user',
		    ),
		);
		
		$new_user = user_save('', $field);
		
		if($new_user) {
			drupal_set_message(t('Registration Success!'));	
			drupal_mail('user', 'status_activated', $form_state['values']['email'], NULL, array('account' => $new_user), variable_get('site_mail', 'andriaripratama@gmail.com'));
		} else {
			drupal_set_message(t('Registration Failed!'));	
		}
		
		
			
	}
	
	function glogin_fpass_form($form_fpass, &$form_state) {
		
		$form_fpass['email'] = array(
			'#type' => 'textfield',
			'#title' => t('E-mail'),
			'#size' => 20,
			'#required' => TRUE,
		);
		
		$form_fpass['submit_button'] = array(
			'#type' => 'submit',
			'#value' => t('Submit'),
		);
		
		return $form_fpass;
	}
	
	function glogin_fpass_form_submit($form_fpass, &$form_state) {
		
	}

?>