<?php

	// leadearboardresource.module
	
	/**
	 *	Implements hook_perm()
	 */
	 
	function leaderboardresource_permission() {
	  // Bangkok, City of Angels, Travel & Leisure Best City 2011
	  // Thaksin and Reds, runaway crimal & convict, ruler of Mordor.
	  return array(
		'leaderboardresource create'=> array('title' => t('leaderboardresource score'),'description' => t('create'),),
		'leaderboardresource view any scores'=> array('title' => t('leaderboardresource view any score'),'description' => t('view any score'),),
		'leaderboardresource view own scores'=> array('title' => t('leaderboardresource view own scores'),'description' => t('view own scores'),),
		'leaderboardresource edit any scores'=> array('title' => t('leaderboardresource edit any score'),'description' => t('edit any score'),),
		'leaderboardresource edit own scores'=> array('title' => t('leaderboardresource edit own scores'),'description' => t('edit own scores'),),
		'leaderboardresource delete any scores'=> array('title' => t('leaderboardresource delete any score'),'description' => t('delete any score'),),
		'leaderboardresource delete own scores'=> array('title' => t('leaderboardresource delete own scores'),'description' => t('delete own scores'),),
	  );
	}
	
	/**
	 *	Gets a score by username
	 */
	 
	 function leaderboardresource_get_score($id) {
		  
          $query = db_select('leaderboard', 'l');
          $query->condition('l.username', $id, '=');
          $query->fields('l', array('id', 'username', 'gameid', 'scores', 'created_at'));
          $item = $query->execute()->fetchAll();
          
          return $item;
          
	 }
	 
	 /**
	  * Writes a score to DB
	  */
	 
	 function leaderboardresource_write_score($score) {
		 
		 $primary_key = !empty($score->id) ? array('id') : NULL;
		 drupal_write_record('leaderboard', $score, $primary_key); 
		 
	 }
	 
	 /**
	  * Delete a score from DB
	  */
	 
	 function leaderboardresource_delete_score($id) {
		 
		 $query = db_delete('leaderboard')->condition('id', $id)->execute();
		 return $query;
		 
	 }
	 
	 /**
	  * hook_services_resources()
	  */
	 
	 function leaderboardresource_services_resources() {
		 
		 return array(
		 	'leaderboard' => array(
		 		'operations' => array(
			 		'retrieve' => array(
			 			'help' => 'Retrieves a score',
			 			'file' => array('file' => 'inc', 'module' => 'leaderboardresource', 'name' => 'leaderboardresource'),
			 			'callback' => '_leaderboardresource_retrieve',
			 			'access callback' => '_leaderboard_access',
			 			'access arguments' => array('view'),
			 			'access arguments append' => FALSE,
			 			'args' => array(
			             	array(
						 		'name' => 'id',
						 		'type' => 'int',
						 		'description' => 'The id of the score to get',
						 		'source' => array('path' => '0'),
						 		'optional' => FALSE,
						 	),
						),
					),
					'create' => array(
						'help' => 'Store a score',
						'file' => array('file' => 'inc', 'module' => 'leaderboardresource', 'name' => 'leaderboardresource'),
						'callback' => '_leaderboardresource_create',
			 			'access arguments' => array('_leaderboard_access'),
			 			'access arguments append' => FALSE,
			 			'args' => array(
			             	array(
						 		'name' => 'data',
						 		'type' => 'struct',
						 		'description' => 'The score object',
						 		'source' => 'data',
						 		'optional' => FALSE,
						 	),
						),
					),
					'update' => array(
						'help' => 'Update a score',
						'file' => array('file' => 'inc', 'module' => 'leaderboardresource', 'name' => 'leaderboardresource'),
						'callback' => '_leaderboardresource_update',
						'access callback' => '_leaderboardresource_access',
			 			'access arguments' => array('update'),
			 			'access arguments append' => TRUE,
			 			'args' => array(
			             	array(
						 		'name' => 'id',
						 		'type' => 'int',
						 		'description' => 'The score id to be update',
						 		'source' => array('path' => 0),
						 		'optional' => FALSE,
						 	),
						 	array(
						 		'name' => 'data',
						 		'type' => 'struct',
						 		'description' => 'The score data object',
						 		'source' => 'data',
						 		'optional' => FALSE,
						 	),
						),
					),
					'delete' => array(
						'help' => 'Delete a score',
						'file' => array('file' => 'inc', 'module' => 'leaderboardresource', 'name' => 'leaderboardresource'),
						'callback' => '_leaderboardresource_delete',
			 			'access arguments' => array('delete'),
			 			'access arguments append' => TRUE,
			 			'args' => array(
			             	array(
						 		'name' => 'id',
						 		'type' => 'int',
						 		'description' => 'The id score to delete',
						 		'source' => array('path' => '0'),
						 		'optional' => FALSE,
						 	),
						),
					),
					'index' => array(
						'help' => 'Retrieves a listing of score',
						'file' => array('file' => 'inc', 'module' => 'leaderboardresource', 'name' => 'leaderboardresource'),
						'callback' => '_leaderboardresource_index',
						'access callback' => 'user_access',
			 			'access arguments' => array('access content'),
			 			'access arguments append' => FALSE,
			 			'args' => array(
			             	array(
						 		'name' => 'pages',
						 		'type' => 'int',
						 		'description' => '',
						 		'source' => array('param' => 'page',),
						 		'optional' => TRUE,
						 		'default value' => 0,
						 	),
						 	array(
						 		'name' => 'parameters',
						 		'type' => 'array',
						 		'description' => '',
						 		'source' => 'param',
						 		'optional' => TRUE,
						 		'default value' => array(),
						 	),
						),
					),
				),
			),
		 );
		 
	 }
	 
?>